version: '3'

services:
  web:
    image: 480271108730.dkr.ecr.ap-south-1.amazonaws.com/empulse_web:latest
    volumes:
      - ../backend:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db: 
    image: 480271108730.dkr.ecr.ap-south-1.amazonaws.com/postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=empulse
      - POSTGRES_PASSWORD=empulse
      - POSTGRES_DB=db

volumes:
  postgres_data:
