version: '3'

services:
  web:
    image: your_account_id.dkr.ecr.your_preferred_region.amazonaws.com/app_repo_name:image_tag
    volumes:
      - ../backend:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db: 
    image: your_account_id.dkr.ecr.your_preferred_region.amazonaws.com/postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=empulse
      - POSTGRES_PASSWORD=empulse
      - POSTGRES_DB=db

volumes:
  postgres_data:
